package igntest

import (
  "encoding/json"
  "net/http"
  "os"
  "regexp"
  "testing"
  "bitbucket.org/ignitionrobotics/ign-go"
)

// Generic Router tests helper functions. To be invoked from
// projects that defines the routes.

// InvalidRouteTestHelper is a helper test function that just invokes
// an invalid route
func InvalidRouteTestHelper(t *testing.T) {
  uri := "/1.0/invalidroute/"
  myJWT := os.Getenv("IGN_TEST_JWT")
  AssertRouteMultipleArgs("GET", uri, nil, http.StatusNotFound, &myJWT, "text/plain; charset=utf-8", t)
  t.Log("InvalidRouteTestHelper run")
}

// OptionsTestHelper is a helper function to test the autogenerated OPTIONS
// urls, given a set of Routes. This function should be called from each specific
// project that defines routes.
func OptionsTestHelper(routes ign.Routes, t *testing.T) {

  for idx := range routes {
    uri := routes[idx].URI
    // Create a valid url. We look for routes containing {path:[a-zA-Z0-9=\\-\\_\\/\\.\\+]+},
    // and only keep the first part (ie. path)
    re := regexp.MustCompile("{([^/]+)?:.+?}")
    uri = re.ReplaceAllString(uri, "$1")
    body, ok := AssertRoute("OPTIONS", uri, http.StatusOK, t)
    t.Log("Detected uri:", uri)

    var parsed map[string]interface{}
    json.Unmarshal(*body, &parsed)

    if !ok {
      t.Fatalf("OPTIONS %s request failed", uri)
    }
    if parsed["name"] != routes[idx].Name {
      t.Fatalf("OPTIONS %s request returned invalid name. Exp: [%s], got: [%s]", uri, routes[idx].Name, parsed["name"])
    }
  }
}
