image: golang:1.8.3

pipelines:
  default:
    - step:
        script:
          - source bitbucket-pipelines-go.sh
          - cd ${IMPORT_PATH}
          - go get -u github.com/golang/lint/golint
          - go version
          - go get
          - lint=$(golint ./... | grep -v ".pb.go") && if [[ ! -z $lint ]]; then echo $lint && exit 1; fi
          - go build
          - go test -covermode=count -coverprofile=count.out
          - go test bitbucket.org/ignitionrobotics/ign-go/test -covermode=count -coverprofile=count-test.out
          - go tool cover -html=count.out -o coverage.html && go tool cover -func=count.out
          - go tool cover -html=count-test.out -o coverage-test.html && go tool cover -func=count-test.out
        services:
          - database

definitions:
  services:
    database:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: root
